data(mtcars)
colnames(mtcars)  
rownames(mtcars)  
mean_mpg <- mean(mtcars$mpg)  
sd_mpg <- sd(mtcars$mpg)      
mean_cyl <- mean(mtcars$cyl)  
sd_cyl <- sd(mtcars$cyl)      
print(paste("Mean of mpg:", mean_mpg))
print(paste("Standard deviation of mpg:", sd_mpg))
print(paste("Mean of cyl:", mean_cyl))
print(paste("Standard deviation of cyl:", sd_cyl))
average_values <- colMeans(mtcars)
print("Column means for all numeric columns:")
print(average_values)
cyl_Mazda_RX4 <- mtcars["Mazda RX4", "cyl"]
print(paste("Cyl value for Mazda RX4:", cyl_Mazda_RX4))
